/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.Inventario;
import ec.edu.ups.modelo.Producto;
import ec.edu.ups.controlador.ControladorCategoria;
import ec.edu.ups.controlador.ControladorInventario;
import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.controlador.ControladorProveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class VentanaEliminarProducto extends javax.swing.JInternalFrame {

    private VentanaBuscarProducto ventanaBuscarProducto;
    private ControladorProducto controladorProducto;
    private ControladorCategoria controladorCategoria;
    private ControladorProveedor controladorProveedor;
    private ControladorInventario controladorInventario;

    public VentanaEliminarProducto(VentanaBuscarProducto vp, String cod) {
        initComponents();
        controladorProducto = new ControladorProducto();
        controladorCategoria = new ControladorCategoria();
        controladorProveedor = new ControladorProveedor();
        controladorInventario = new ControladorInventario();
        vp = ventanaBuscarProducto;
        txtCodigoEliminarBuscar.setText(cod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtCodigoEliminar = new javax.swing.JTextField();
        txtDescripcionEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        txtCodigoEliminarBuscar = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtPrecioEliminar = new javax.swing.JTextField();
        txtCategoriaEliminar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtProveedorEliminar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Eliminar Producto");
        setToolTipText("");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("Codigo:");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Descripcion:");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("Precio:");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Categoria:");

        txtCodigoEliminar.setEditable(false);
        txtCodigoEliminar.setEnabled(false);

        txtDescripcionEliminar.setEditable(false);
        txtDescripcionEliminar.setEnabled(false);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/recursos/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/recursos/buscar.png"))); // NOI18N
        btnBuscarE.setText("Buscar");
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setText("Codigo:");

        txtPrecioEliminar.setEditable(false);
        txtPrecioEliminar.setEnabled(false);
        txtPrecioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioEliminarActionPerformed(evt);
            }
        });

        txtCategoriaEliminar.setEditable(false);
        txtCategoriaEliminar.setEnabled(false);
        txtCategoriaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaEliminarActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/recursos/canselar.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Proveedor:");

        txtProveedorEliminar.setEditable(false);
        txtProveedorEliminar.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28)
                            .addComponent(jLabel33)
                            .addComponent(jLabel29)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnEliminar)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCategoriaEliminar)
                            .addComponent(txtDescripcionEliminar)
                            .addComponent(txtCodigoEliminarBuscar)
                            .addComponent(txtCodigoEliminar)
                            .addComponent(txtPrecioEliminar)
                            .addComponent(txtProveedorEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(153, 153, 153))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnBuscarE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(txtCodigoEliminarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(txtCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtDescripcionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtPrecioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtCategoriaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtProveedorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCategoriaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaEliminarActionPerformed

    private void txtPrecioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEliminarActionPerformed

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
        // TODO add your handling code here:
        Producto p = controladorProducto.BuscarProductoCod(txtCodigoEliminarBuscar.getText());
        if (p.getId() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Producto no disponible");
        } else {
            txtCodigoEliminar.setText(String.valueOf(p.getId()));
            txtDescripcionEliminar.setText(p.getDescripcion());
            txtPrecioEliminar.setText(String.valueOf(p.getPrecio()));
            txtProveedorEliminar.setText(p.getProveedor().getNombre());
            txtCategoriaEliminar.setText(p.getCategoria().getDescripcion());
            Inventario inventario = controladorInventario.BuscarInventarioProducto(Integer.valueOf(txtCodigoEliminar.getText()));
            controladorInventario.eliminarInventario(inventario, inventario.getId());
        }
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        controladorProducto.conexion();
        Producto c = controladorProducto.BuscarProductoCod(txtCodigoEliminarBuscar.getText());
        int confirmar = JOptionPane.showConfirmDialog(rootPane, "Seguro que desea eliminar el producto: " + c.getDescripcion());
        if (confirmar == 0) {
            controladorProducto.eliminarProducto(c, c.getId());
            controladorProducto.desconectar();
            txtDescripcionEliminar.setText("");
            txtCodigoEliminarBuscar.setText("");
            txtCodigoEliminar.setText("");
            txtPrecioEliminar.setText("");
        }
        if (confirmar == 1 || confirmar == 2) {
            JOptionPane.showMessageDialog(rootPane, "Eliminacion Cancelada");
            controladorProducto.desconectar();
            txtDescripcionEliminar.setText("");
            txtCodigoEliminarBuscar.setText("");
            txtCodigoEliminar.setText("");
            txtPrecioEliminar.setText("");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JTextField txtCategoriaEliminar;
    private javax.swing.JTextField txtCodigoEliminar;
    private javax.swing.JTextField txtCodigoEliminarBuscar;
    private javax.swing.JTextField txtDescripcionEliminar;
    private javax.swing.JTextField txtPrecioEliminar;
    private javax.swing.JTextField txtProveedorEliminar;
    // End of variables declaration//GEN-END:variables
}
