/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.Categoria;
import ec.edu.ups.modelo.Inventario;
import ec.edu.ups.modelo.Producto;
import ec.edu.ups.modelo.Proveedor;
import ec.edu.ups.controlador.ControladorCategoria;
import ec.edu.ups.controlador.ControladorInventario;
import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.controlador.ControladorProveedor;

import java.awt.Desktop;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.plaf.DesktopPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class VentanaBuscarProducto extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private VentanaPrincipal ventanaPrincipal;
    private ControladorProducto controladorProducto;
    private ControladorInventario controladorInventario;
    private ControladorCategoria controladorCategoria;
    private ControladorProveedor controladorProveedor;
    DefaultTableModel model1 = new DefaultTableModel();
    //JDesktopPane desktopPane;
    private VentanaCrearProducto ventanaCrearProducto;
    private VentanaEliminarProducto ventanaEliminarProducto;
    private VentanaModificarProducto ventanaModificarProducto;

    private String cod;

    /**
     * Creates new form VentanaBuscarProducto
     */
    public VentanaBuscarProducto(VentanaPrincipal vp) {
        initComponents();
        vp = ventanaPrincipal;
        controladorProducto = new ControladorProducto();
        controladorInventario = new ControladorInventario();
        controladorCategoria = new ControladorCategoria();
        controladorProveedor = new ControladorProveedor();
    //    desktopPane = new JDesktopPane();
        ventanaCrearProducto = new VentanaCrearProducto(this);
        //cod="1";

        model1.addColumn("CODIGO");
        model1.addColumn("DESCRIPCION");
        model1.addColumn("PRECIO");
        model1.addColumn("CATEGORIA");
        model1.addColumn("STOCK");
        //model1.addColumn("DESCUENTO");
        //model1.addColumn("PROVEEDOR");
        jTable1.setModel(model1);
        listarProductos();

        List<Categoria> lista = controladorCategoria.listar();
        for (Categoria p : lista) {
            cbxCategoriaIns.addItem(p.getDescripcion());
        }
        List<Proveedor> listaProv = controladorProveedor.listar();
        for (Proveedor prov : listaProv) {
            cbxProveedorIns.addItem(prov.getNombre());

        }
    }

    public void buscarProductos(String producto) {
        try {
            String[] titulo = {"CODIGO", "DESCRIPCION", "PRECIO", "CATEGORIA", "STOCK"};
            modelo = new DefaultTableModel(null, titulo);
            List<Producto> lista = controladorProducto.BuscarProductoLik(producto);
            for (Producto a : lista) {
                Object[] datos = new Object[5];
                datos[0] = a.getCodigo();
                datos[1] = a.getDescripcion();
                datos[2] = a.getCategoria().getDescripcion();
                datos[3] = a.getPrecio();
                datos[4] = a.getCantidad();

                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (Exception ex) {
        }

    }

    public void listarProductos() {

        jTable1.getModel();
        int ab = jTable1.getRowCount() - 1;
        for (int i = ab; i >= 0; i--) {
            model1.removeRow(model1.getRowCount() - 1);
        }

        List<Producto> lista = controladorProducto.listar();
        for (Producto a : lista) {
            Object[] datos = new Object[15];
            datos[0] = a.getCodigo();
            datos[1] = a.getDescripcion();
            datos[2] = a.getCategoria().getDescripcion();
            datos[3] = a.getPrecio();
            datos[4] = a.getCantidad();
            datos[5] = a.getProveedor().getNombre();
            model1.addRow(datos);
        }
        jTable1.setModel(model1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcionIns = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioInser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxCategoriaIns = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxProveedorIns = new javax.swing.JComboBox<>();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento de productos");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Descripcion");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Precio");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Categoria");

        cbxCategoriaIns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbxCategoriaIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxCategoriaInsMousePressed(evt);
            }
        });
        cbxCategoriaIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaInsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Proveedor");

        cbxProveedorIns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbxProveedorIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxProveedorInsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxProveedorInsMousePressed(evt);
            }
        });
        cbxProveedorIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProveedorInsActionPerformed(evt);
            }
        });

        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/recursos/buscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcionIns)
                    .addComponent(txtPrecioInser)
                    .addComponent(cbxCategoriaIns, 0, 208, Short.MAX_VALUE)
                    .addComponent(cbxProveedorIns, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(335, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescripcionIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecioInser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbxCategoriaIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbxProveedorIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/recursos/agregar.png"))); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/recursos/madificar.png"))); // NOI18N
        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/recursos/eliminar.png"))); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/recursos/canselar.png"))); // NOI18N
        jButton4.setText("CANCELAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyReleased
        // TODO add your handling code here:
        buscarProductos(txtBuscarProducto.getText());
    }//GEN-LAST:event_txtBuscarProductoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txtDescripcionIns.getText().equals("") && !txtPrecioInser.getText().equals("")) {
            Producto p = new Producto();
            p.setId(controladorProducto.obtenerCodigo());
         //   controladorProducto.conexion();
            p.setDescripcion(txtDescripcionIns.getText());
            String cate = (String) cbxCategoriaIns.getSelectedItem();
            String prove = (String) cbxProveedorIns.getSelectedItem();
            Categoria c = controladorCategoria.BuscarCategoriaNombre(cate);
            Proveedor proveedor = controladorProveedor.buscarP(prove);
            p.setCategoria(c);
            p.setProveedor(proveedor);
            p.setPrecio(Double.valueOf(txtPrecioInser.getText()));
            String codigo = controladorProducto.Codigo(txtDescripcionIns.getText(), cate);
            p.setCodigo(codigo);
            System.out.println("lslll "+codigo);
            controladorProducto.registrarProducto(p);
           // controladorProducto.desconectar();
            
            Producto producto = controladorProducto.BuscarProductoCod(p.getCodigo());
            System.out.println("p.get "+p.getCodigo());
            System.out.println("mkskxs "+producto.getId());
            if (producto.getCodigo()==(p.getCodigo())) {
                Inventario inventario = new Inventario();
                inventario.setProducto(p);
                inventario.setPrecioEntrada(p.getPrecio());
                inventario.setId(controladorInventario.obtenerCodigo());
                inventario.setTotalCantidad(p.getCantidad());

                controladorInventario.conexion();
                controladorInventario.registrarInventario(inventario);
                controladorInventario.desconectar();
            }

            // txtCodigoInsertar.setText(String.valueOf(controladorProducto.obtenerCodigo()));
            txtDescripcionIns.setText("");
            txtPrecioInser.setText("");
            listarProductos();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione todos los campos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // cod = "1";
        System.out.println("codigo  " + cod);
        if (cod != null) {
            ventanaModificarProducto = new VentanaModificarProducto(this, cod);
            if (!this.getDesktopPane().isAncestorOf(ventanaModificarProducto)) {
                this.getDesktopPane().add(ventanaModificarProducto);
            } else {
                this.getDesktopPane().setSelectedFrame(ventanaModificarProducto);
            }
            this.ventanaModificarProducto.show();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un producto en la tabla");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:        
        if (cod != null) {
            Producto c = controladorProducto.BuscarProductoCod(cod);
            System.out.println(" codigo :" + cod + " " + c.getId());
            if (c.getCantidad()<=0) {
                int confirmar = JOptionPane.showConfirmDialog(rootPane, "Seguro que desea eliminar el producto: " + c.getDescripcion());
                System.out.println("00000000000 "+confirmar);
                if (confirmar == 0) {
                    controladorProducto.conexion();
                    controladorProducto.eliminarProducto(c, c.getId());
                    controladorProducto.desconectar();
                    Inventario inve = controladorInventario.BuscarInventarioProducto(c.getId());
                    controladorInventario.conexion();
                    controladorInventario.eliminarInventario(inve, inve.getId());
                    controladorInventario.desconectar();
                    listarProductos();

                }
                if (confirmar == 1 || confirmar == 2) {
                    JOptionPane.showMessageDialog(rootPane, "Eliminacion Cancelada");
                    controladorProducto.desconectar();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar producto " + c.getDescripcion() + " con stock de " + c.getCantidad());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un producto en la tabla");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String valor = "";
        int totalRow = jTable1.getSelectedRow();
//        for (int i = 0; i <= (totalRow); i++) {
        cod = jTable1.getValueAt(totalRow, 0).toString();
        //      }

        System.out.println("jsjsjs " + valor);

    }//GEN-LAST:event_jTable1MouseClicked

    private void cbxCategoriaInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaInsActionPerformed
        try {
            String txt = (String) cbxCategoriaIns.getSelectedItem();
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaInsActionPerformed

    private void cbxProveedorInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProveedorInsActionPerformed
        try {
            String txt = (String) cbxProveedorIns.getSelectedItem();
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProveedorInsActionPerformed

    private void cbxProveedorInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxProveedorInsMouseClicked
        cbxProveedorIns.removeAllItems();
        List<Proveedor> listaProv = controladorProveedor.listar();
        for (Proveedor pro : listaProv) {
            cbxProveedorIns.addItem(pro.getNombre());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProveedorInsMouseClicked

    private void cbxCategoriaInsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoriaInsMousePressed
        // TODO add your handling code here:
        cbxCategoriaIns.removeAllItems();
        List<Categoria> lista = controladorCategoria.listar();
        for (Categoria p : lista) {
            cbxCategoriaIns.addItem(p.getDescripcion());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaInsMousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbxProveedorInsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxProveedorInsMousePressed
    }//GEN-LAST:event_cbxProveedorInsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCategoriaIns;
    private javax.swing.JComboBox<String> cbxProveedorIns;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtDescripcionIns;
    private javax.swing.JTextField txtPrecioInser;
    // End of variables declaration//GEN-END:variables

}
